# Schema for the configuration files of the role_content module.
role_content.settings:
  type: config_object
  label: 'role_content settings'
  mapping:
    example:
      type: string
      label: 'Example'
