# Schema for the configuration files of the reference module.
reference.settings:
  type: config_object
  label: 'reference settings'
  mapping:
    example:
      type: string
      label: 'Example'
