# Schema for the configuration files of the clonetask module.
clonetask.settings:
  type: config_object
  label: 'clonetask settings'
  mapping:
    example:
      type: string
      label: 'Example'
